"""Stable requirement type constants for JD parsing and classification."""

from __future__ import annotations


TECH_SKILL = "TECH_SKILL"
TOOL_PLATFORM = "TOOL_PLATFORM"
EXPERIENCE_REQUIREMENT = "EXPERIENCE_REQUIREMENT"
EDUCATION_REQUIREMENT = "EDUCATION_REQUIREMENT"
CERTIFICATION_REQUIREMENT = "CERTIFICATION_REQUIREMENT"
LANGUAGE_REQUIREMENT = "LANGUAGE_REQUIREMENT"
SOFT_SKILL = "SOFT_SKILL"
RESPONSIBILITY_CONTEXT = "RESPONSIBILITY_CONTEXT"
DOMAIN_CONTEXT = "DOMAIN_CONTEXT"
UNKNOWN_REQUIREMENT = "UNKNOWN_REQUIREMENT"

MUST_HAVE_PRIORITY = "must_have"
NICE_TO_HAVE_PRIORITY = "nice_to_have"
CONTEXT_PRIORITY = "context"

TECHNICAL_REQUIREMENT_TYPES = {
    TECH_SKILL,
    TOOL_PLATFORM,
    CERTIFICATION_REQUIREMENT,
    UNKNOWN_REQUIREMENT,
}
